@echo off
echo Starting Backend...
start cmd /k "cd backend && venv\Scripts\activate && python -m uvicorn main:app --reload --port 8000"
timeout /t 3
echo Starting Frontend...
start cmd /k "cd frontend && npm run dev"
